In [1]:
import pandas as pd

# Q1

In [4]:
pd.__version__

'2.2.3'

In [5]:
df = pd.read_csv('laptops.csv')

# Q2

In [7]:
print('Len of DF: ', len(df))

Len of DF:  2160


# Q3

In [8]:
df.head()

Laptop Status   Brand  \
0  ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...    New    Asus   
1  Alurin Go Start Intel Celeron N4020/8GB/256GB ...    New  Alurin   
2  ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...    New    Asus   
3  MSI Katana GF66 12UC-082XES Intel Core i7-1270...    New     MSI   
4  HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...    New      HP   

        Model            CPU  RAM  Storage Storage type       GPU  Screen  \
0  ExpertBook  Intel Core i5    8      512          SSD       NaN    15.6   
1          Go  Intel Celeron    8      256          SSD       NaN    15.6   
2  ExpertBook  Intel Core i3    8      256          SSD       NaN    15.6   
3      Katana  Intel Core i7   16     1000          SSD  RTX 3050    15.6   
4         15S  Intel Core i5   16      512          SSD       NaN    15.6   

  Touch  Final Price  
0    No      1009.00  
1    No       299.00  
2    No       789.00  
3    No      1199.00  
4    No       669.01

In [9]:
df['Brand'].nunique()

27

# Q4

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2156 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


In [11]:
#no of columns with na
# is three
columns = df.columns.tolist()

In [15]:
na_col = [col  for col in columns if df[col].isna().sum() !=0 ]

In [16]:
na_col

['Storage type', 'GPU', 'Screen']

In [17]:
print('No of NAN cols: ', len(na_col))

No of NAN cols:  3


# Q5

In [18]:
# max Final Price
df[df['Brand'] == 'Dell']['Final Price'].max()

np.float64(3936.0)

# Q6

In [19]:
s_median = df['Screen'].median()
s_median

np.float64(15.6)

In [20]:
#frequency 
value_counts = df['Screen'].value_counts()
max_frequency = value_counts.max()
print(f"The frequency of the most common value(s) is: {max_frequency}")

The frequency of the most common value(s) is: 1009


In [24]:
value_counts.index[0]

np.float64(15.6)

In [25]:
most_common = value_counts.nlargest(1)
most_common

Screen
15.6    1009
Name: count, dtype: int64

In [29]:
# calculate the most frequent value of the same Screen column
most_frequent_value = df['Screen'].mode()[0]
most_frequent_value

np.float64(15.6)

In [27]:
df['Screen'].mode()

0    15.6
Name: Screen, dtype: float64

In [30]:
#Use fillna method to fill the missing values in Screen column with the most frequent value from the previous step
df['Screen'] = df['Screen'].fillna(most_frequent_value)

In [31]:
#calculate the median value of Screen once again
new_median = df['Screen'].median()
new_median

np.float64(15.6)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2160 entries, 0 to 2159
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   Laptop        2160 non-null   object 
 1   Status        2160 non-null   object 
 2   Brand         2160 non-null   object 
 3   Model         2160 non-null   object 
 4   CPU           2160 non-null   object 
 5   RAM           2160 non-null   int64  
 6   Storage       2160 non-null   int64  
 7   Storage type  2118 non-null   object 
 8   GPU           789 non-null    object 
 9   Screen        2160 non-null   float64
 10  Touch         2160 non-null   object 
 11  Final Price   2160 non-null   float64
dtypes: float64(2), int64(2), object(8)
memory usage: 202.6+ KB


# Q7

In [44]:
#Select all the "Innjoo" laptops from the dataset.
#Select only columns RAM, Storage, Screen.
df2 = df[df['Laptop'].str.contains('Innjoo')][['RAM', 'Storage', 'Screen']]
df2.head()

RAM  Storage  Screen
1480    4       64    14.1
1481    6       64    14.1
1482    6      128    14.1
1483    6      128    14.1

In [45]:
X = df2.to_numpy()

In [46]:
X

array([[  4. ,  64. ,  14.1],
       [  6. ,  64. ,  14.1],
       [  6. , 128. ,  14.1],
       [  6. , 128. ,  14.1]])

In [71]:
TX = X.T

In [72]:
TX

array([[  4. ,   6. ,   6. ,   6. ],
       [ 64. ,  64. , 128. , 128. ],
       [ 14.1,  14.1,  14.1,  14.1]])

In [68]:
import numpy 

In [78]:
XTX = numpy.dot(TX, X)
XTX

array([[  124.  ,  2176.  ,   310.2 ],
       [ 2176.  , 40960.  ,  5414.4 ],
       [  310.2 ,  5414.4 ,   795.24]])

In [85]:
#Compute the inverse of XTX
XTX_inv = numpy.linalg.inv(XTX)
XTX_inv

array([[ 5.00000000e-01, -7.81250000e-03, -1.41843972e-01],
       [-7.81250000e-03,  3.66210938e-04,  5.54078014e-04],
       [-1.41843972e-01,  5.54078014e-04,  5.28142448e-02]])

In [86]:
y = numpy.array([1100, 1300, 800, 900, 1000, 1100])
y

array([1100, 1300,  800,  900, 1000, 1100])

In [83]:
#Multiply the inverse of XTX with the transpose of X
numpy.dot(inverse, X.T)

array([[-5.00000000e-01,  5.00000000e-01, -1.85529291e-16,
        -1.85529291e-16],
       [ 5.08690743e-17, -1.56250000e-02,  7.81250000e-03,
         7.81250000e-03],
       [ 2.12765957e-01, -7.09219858e-02, -3.54609929e-02,
        -3.54609929e-02]])

In [91]:
w = np.dot(XTX_inv, X.T)